### ISSUE TITLE
Platform dependend storage file location

### ISSUE THREAD

**Issue by juho05** [Zersaeger/Passwordmanager#1]
Currently the storage location for password files is hardcoded to "x:\Passwords\", which only works on Windows machines with a partition mounted to "X:". It would be better to store the passwords in a platform independent standard location or to make the location configurable by the user.

**Comment by Zersaeger** [comment]
Thanks for the feedback. I'll change that soon

**Comment by juho05** [comment]
Wow, such a nice maintainer <3
